// ── data.js — all static content ─────────────────────────────────────────
// Edit this file to update any text, jobs, tools, or projects on the site.

export const STATS = [
  { display: '6+',  count: '6',  suffix: '+', label: 'Yrs leading teams' },
  { display: '2+',  count: '2',  suffix: '+', label: 'Yrs in fintech'    },
  { display: '80%', count: '80', suffix: '%', label: 'Masters average', accent: true },
  { display: '3rd', count: null,              label: 'RoboCup 2024' },
];

// How I work — operating principles shown on the home page.
export const PRINCIPLES = [
  ['Read before you theorise.',        'Logs first, theory second. Most incidents are already explained in the data — the discipline is looking before guessing.'],
  ['Communication is half the fix.',   'During an outage, a client who knows what’s happening and when trusts the process. Managing that is as much the job as the resolution.'],
  ['Calm is a skill, not a temperament.', 'Earned shift by shift on a retail front end long before a live banking incident. It’s the thing that holds when systems don’t.'],
  ['Build the tool the second time.',  'If I’ve done something by hand mid-incident twice, it becomes a tool. Most of what I’ve built started exactly there.'],
];

export const CATS = [
  ['all',     'Everything'],
  ['banking', 'Banking systems'],
  ['ops',     'Operations'],
  ['network', 'Networking'],
  ['code',    'Development'],
  ['client',  'Client & leadership'],
  ['study',   'Studying now'],
];

export const TOOLS = [
  { name: 'Core banking platforms', cat: 'banking', cadence: 'Daily',
    what: 'The platform that runs a bank’s accounts, transactions, interest and compliance.',
    how: 'Ultradata’s core banking platform serves mutual banks and credit unions across Australia. Most cases that reach me start somewhere inside it.' },
  { name: 'UniVerse DB', cat: 'banking', cadence: 'Daily',
    what: 'A multidimensional NoSQL database by Rocket Software, still carrying a lot of legacy banking.',
    how: 'I administer UniVerse environments — port status, locks, performance — and wrote a tool to read its diagnostic captures because doing it by hand mid-incident is slow.',
    project: 'uvdiag-lock-analysis', projectLabel: 'UVDiag Lock Analysis' },
  { name: 'Microsoft SQL Server', cat: 'banking', cadence: 'Daily',
    what: 'Microsoft’s relational database engine.',
    how: 'Reporting and AML databases across client environments: querying, maintenance, and tracing where a number actually came from.' },
  { name: 'AML systems', cat: 'banking', cadence: 'Regular',
    what: 'Anti-money-laundering monitoring that watches transactions for suspicious patterns under regulatory obligation.',
    how: 'I maintain the reporting databases behind these systems across client banking environments.' },
  { name: 'NPP payments', cat: 'banking', cadence: 'Regular',
    what: 'The New Payments Platform — Australia’s real-time payments infrastructure.',
    how: 'When NPP fails, customers can’t move money instantly. These are the incidents that don’t wait for business hours.' },
  { name: 'Production deployments & upgrades', cat: 'ops', cadence: 'Regular',
    what: 'Rolling technical changes, releases and version upgrades out to live client systems.',
    how: 'I implement changes directly in client production environments and handle software/patch upgrades on their systems — coordinated around the client’s go-live window, not just tested in a lab.' },
  { name: 'SSL/TLS certificates', cat: 'network', cadence: 'Daily',
    what: 'The certificates encrypting traffic between banking applications and the people using them.',
    how: 'Renewals and updates across live and development environments. An expired cert takes a client-facing service down with no warning, which is exactly why I built a monitor for it.',
    project: 'ssl-monitor', projectLabel: 'SSL/TLS Certificate Monitor' },
  { name: 'IIS', cat: 'ops', cadence: 'Daily',
    what: 'Internet Information Services — Microsoft’s web server.',
    how: 'Sites, application pools, bindings and certificates for client-facing banking web applications.' },
  { name: 'Log analysis', cat: 'ops', cadence: 'Daily',
    what: 'IIS logs, application traces and Windows Event Viewer.',
    how: 'Read the logs before forming a theory. I did it often enough that I built a viewer to make the pattern show up faster.',
    project: 'iis-log-viewer', projectLabel: 'IIS Log Viewer' },
  { name: 'Outage response', cat: 'ops', cadence: 'Regular',
    what: 'Triage, diagnosis, stakeholder communication, resolution, write-up.',
    how: 'On-call as the escalation point for over a year — critical banking incidents don’t wait for business hours, so I don’t either: 2am pages and weekend calls come with the territory. Every minute of downtime has a cost. Staying calm and communicating clearly is most of the work.' },
  { name: 'Unix & scripting', cat: 'ops', cadence: 'Regular',
    what: 'Command line work plus shell and batch automation.',
    how: 'Server-side troubleshooting, and automating the repetitive parts of system administration across Windows and Unix.' },
  { name: 'Server networking', cat: 'network', cadence: 'Regular',
    what: 'TCP/IP fundamentals and how traffic moves between servers, clients and services.',
    how: 'Working out why a client environment can’t reach something it reached yesterday.' },
  { name: 'DNS & name resolution', cat: 'network', cadence: 'Regular',
    what: 'How hostnames map to addresses, and what breaks when they don’t.',
    how: 'Checking records and resolution first when a service is “down” but the server itself is fine.' },
  { name: 'Firewalls & ports', cat: 'network', cadence: 'Regular',
    what: 'Rules that decide which traffic may reach which service, and on which port.',
    how: 'Confirming a port is open end to end before blaming the application.' },
  { name: 'Network troubleshooting', cat: 'network', cadence: 'Regular',
    what: 'Isolating a fault layer by layer: connectivity, name resolution, ports, then the application.',
    how: 'Narrowing a vague “it can’t connect” report to a specific cause during a live incident.' },
  { name: 'Git', cat: 'ops', cadence: 'Regular',
    what: 'Version control.',
    how: 'My own tools, and the public open-source release of the RoboCup codebase.',
    project: 'robocup', projectLabel: 'RoboCup Capstone' },
  { name: 'HTML, CSS & JavaScript', cat: 'code', cadence: 'Regular',
    what: 'The core languages of the web: structure, styling and behaviour in the browser.',
    how: 'Behind this site and my browser-based tools, written as plain vanilla JavaScript without a framework.' },
  { name: 'Python', cat: 'code', cadence: 'Regular',
    what: 'A general-purpose language for scripting, automation and security tooling.',
    how: 'Behind my SSL/TLS Certificate Monitor, and the language of the AI foundations work at RMIT.',
    project: 'ssl-monitor', projectLabel: 'SSL/TLS Certificate Monitor' },
  { name: 'Node.js', cat: 'code', cadence: 'Regular',
    what: 'JavaScript outside the browser, for scripts, tooling and servers.',
    how: 'Build scripts and tooling around my projects, including this site’s build and prerender step.' },
  { name: '.NET', cat: 'code', cadence: 'Regular',
    what: 'Microsoft’s application platform, used with C# and related languages.',
    how: 'The Microsoft-stack side of the work, alongside IIS and SQL Server in client environments.' },
  { name: 'BASIC', cat: 'code', cadence: 'Regular',
    what: 'The BASIC language family, still found in long-lived business and banking systems.',
    how: 'Reading and following BASIC code to trace how a legacy banking process behaves when something goes wrong.' },
  { name: 'Client communication', cat: 'client', cadence: 'Daily',
    what: 'Turning technical status into something a client can act on.',
    how: 'Priority issues on site and online, plus regular walkthroughs of ongoing cases. Managing expectations during an incident is a skill of its own.' },
  { name: 'Project team collaboration', cat: 'client', cadence: 'Regular',
    what: 'Working alongside project teams on rollouts, upgrades and client go-lives.',
    how: 'Feeding what support sees in live environments back into project plans, and picking up the handover once a change goes live.' },
  { name: 'CRM team collaboration', cat: 'client', cadence: 'Regular',
    what: 'Coordinating with the CRM and client-relationship side of the business.',
    how: 'Keeping client records, case history and expectations aligned so nobody has to repeat themselves to the client.' },
  { name: 'Development team collaboration', cat: 'client', cadence: 'Regular',
    what: 'Bridging support and development to get real defects fixed.',
    how: 'Escalating with clear reproduction steps, logs and impact, so developers can act without a round of questions.' },
  { name: 'Case ownership', cat: 'client', cadence: 'Regular',
    what: 'Carrying a complex case from first contact to close.',
    how: 'Taking on the cases that haven’t resolved, coordinating across the team, and staying the point of contact until they’re done.' },
  { name: 'Mentoring & onboarding', cat: 'client', cadence: 'Regular',
    what: 'Getting new technical staff effective inside a complex environment.',
    how: 'Context first, then tooling — backed by knowledge base material so it doesn’t depend on me being in the room.' },
  { name: 'Risk governance', cat: 'study', cadence: 'Learning',
    what: 'How an organisation identifies, assesses and governs cyber risk at scale.',
    how: 'My UNSW specialisation, and the reason I’m studying at all: the move from fixing incidents to preventing them.' },
  { name: 'Compliance frameworks', cat: 'study', cadence: 'Learning',
    what: 'ISO 27001, NIST, and the ACSC Essential Eight.',
    how: 'How an organisation demonstrates it’s doing the work. Increasingly the language banking clients ask questions in.' },
  { name: 'Threat modelling', cat: 'study', cadence: 'Learning',
    what: 'STRIDE, attack trees and data flow analysis.',
    how: 'Applied end to end across a 59-page security engineering analysis of QR code systems.',
    project: 'qr-security', projectLabel: 'QR Code Security Analysis' },
];

export const EXPERIENCE = [
  {
    role:     'Technical Support Consultant',
    company:  'Ultradata Australia',
    loc:      'Malvern, Victoria',
    dates:    'Feb 2024 — Present',
    context:  'Ultradata powers the technology behind mutual banks and credit unions across Australia — core banking, payment infrastructure and AML compliance systems. When systems fail in banking, real people feel it. This is the team that fixes it.',
    metrics:  [['30+', 'Cases / month'], ['10+', 'Prod deployments'], ['50+', 'On-call incidents'], ['#1', 'Escalation point']],
    points: [
      'Meet clients on priority issues — on site and online — and walk through ongoing cases with them',
      'Owned hundreds of critical tickets end to end, from first contact through to resolution',
      'Implement technical changes and releases directly into client production environments',
      'Install and upgrade client systems to new software versions and patch releases',
      'Maintain SQL databases including reporting and AML systems across client environments',
      'Administer UniVerse database environments for performance and uptime',
      'Manage SSL/TLS certificates across live and development environments',
      'Configure IIS for hosting and troubleshooting client-facing web applications',
      'Respond to application outages and NPP payment failures under time pressure',
      'Write knowledge base and technical documentation to sharpen team efficiency',
      'Onboarded 5+ new team members, giving them the context to come up to speed fast',
    ],
  },
  {
    role:    'Front End Supervisor',
    company: 'Woolworths',
    loc:     'Highett, Victoria',
    dates:   'Aug 2018 — Nov 2024',
    context: 'Six years of managing people, pressure and process — before a single SQL query. The instinct for calm communication and holding a team together when things go wrong was built here.',
    metrics: [['6 yrs', 'Front-end lead'], ['Team', 'Trained & led']],
    points: [
      'Led and supervised front-end operations at consistently high service standards',
      'Trained and mentored new and existing staff, improving team efficiency',
      'Managed cash handling and reconciliation with minimal discrepancies',
      'Resolved customer escalations with solutions that kept trust intact',
      'Identified workflow bottlenecks and cut wait times',
    ],
  },
  {
    role:    'Capstone Team Member',
    company: 'RMIT RedBackBots',
    loc:     'RMIT University, Melbourne',
    dates:   'Jul — Nov 2023',
    badge:   '3rd Place · Intl',
    website: 'https://redbackbots.com/',
    context: 'An RMIT team that took on the world, finishing third in the Challenge Shield Division at the 2024 international RoboCup — and learning what it takes to deliver against real deadlines.',
    metrics: [['3rd', 'Intl 2024'], ['Code', 'Open-sourced']],
    points: [
      'Led a multidisciplinary team preparing robots for the 2024 competition',
      'Developed marketing strategy and acquired sponsors',
      'Managed project timelines using Agile methodologies',
      'Helped drive the 2023 public code release — the team’s first open-source contribution',
    ],
  },
];

export const WORK_CATEGORIES = [
  ['Banking systems',      ['Core banking platforms', 'UniVerse DB', 'Microsoft SQL Server', 'NPP payments']],
  ['Operations',           ['Outage response', 'SSL/TLS management', 'IIS configuration', 'Log analysis']],
  ['Client & governance',  ['Client communication', 'AML & compliance systems', 'Risk governance', 'Mentoring & onboarding']],
];

export const STORY = [
  {
    chapter: 'Leadership before tech',
    period:  '2018 — 2024',
    body:    'It didn’t start in IT. Six years supervising the front end at Woolworths — managing teams, de-escalating difficult situations, holding a line on a bad shift. Calm under pressure isn’t a personality trait; it’s earned, shift by shift, and it was earned here.',
  },
  {
    chapter: 'Learning the technology',
    period:  '2021 — 2023',
    body:    'RMIT’s Bachelor of Information Technology gave those instincts a vocabulary: systems thinking, database design, security fundamentals, software engineering. The degree connected the dots and opened the door into fintech.',
  },
  {
    chapter: 'Joining Ultradata',
    period:  'Feb 2024 — now',
    body:    'Ultradata Australia provides core banking systems, payment infrastructure and AML compliance platforms to mutual banks and credit unions across the country. I work priority issues directly with clients — on site and online — walk through ongoing cases with them, and step into wider team duties when they’re needed. When these systems go down, the consequences aren’t abstract.',
  },
  {
    chapter: 'The next chapter',
    period:  'Now → 2028',
    body:    'A Master of Cybersecurity at UNSW, averaging 80%, is the natural progression from responding to incidents to preventing them. It runs alongside the day job rather than replacing it — I’m still at Ultradata, still on live banking cases, and the study keeps landing back in the same place: certificates, access, logs, the systems I already have my hands in. The goal is security leadership — not just someone who can fix things, but someone who can build organisations that are resilient before they break.',
  },
];

export const EDUCATION = {
  unsw: {
    status:         'In progress · est. Mar 2028',
    degree:         'Master of Cybersecurity',
    specialisation: 'UNSW Sydney · online · Risk Governance &amp; Management',
    average:        '80%',
    body: `A 12-course online program built to develop senior security capability. The Risk
      Governance &amp; Management track is aimed at professionals moving toward strategic,
      compliance-oriented security leadership — how organisations identify, assess and
      govern cyber risk at scale.`,
    grid: [
      ['Program structure',    '12 courses across core foundations and a chosen specialisation, including a capstone integrating real-world security challenges.'],
      ['Specialisation focus', 'GRC frameworks, cyber risk strategy, compliance standards and security leadership.'],
      ['Career direction',     'Positioned for security analyst, architect, risk manager and CISO-track roles across finance, government and tech.'],
      ['Why now',              'Understanding how systems get compromised is the first step to making them resilient — the natural next move after two years inside banking incidents.'],
    ],
    units: [
      ['Foundations of Cyber Security', 'Core concepts: the CIA triad, common threats and attacks, and the security controls that defend systems and data.'],
      ['Governance, Risk &amp; Compliance', 'How organisations set security policy, assess risk and meet frameworks and regulatory obligations.'],
      ['Cyber Risk Strategy', 'Identifying, quantifying and prioritising cyber risk, then choosing how to treat it at an organisational level.'],
      ['Security Management', 'Running a security program: controls, incident response, metrics and aligning security with business goals.'],
      ['Threat Modelling', 'Structured analysis of how a system can be attacked, to find and rank weaknesses before they are exploited.'],
      ['Digital Forensics', 'Collecting and analysing digital evidence after an incident while preserving its integrity.'],
      ['Cybersecurity Law &amp; Ethics', 'Legal duties, privacy and breach-notification rules, and the ethical limits of security work.'],
      ['Capstone Project', 'An integrating project applying the full program to a real-world security challenge.'],
    ],
  },
  rmit: {
    status:      'Completed · Mar 2021 — Nov 2023',
    degree:      'Bachelor of Information Technology',
    institution: 'RMIT University · Melbourne City Campus',
    body: `A three-year, industry-focused degree built around real-world problem solving,
      from websites to enterprise systems to network programming, with work-integrated
      learning embedded throughout. It built the technical foundation that made the move
      into Ultradata’s banking environment possible.`,
    grid: [
      ['Learning approach', 'Practical, industry-based learning with real group projects and lecturers working in the field.'],
      ['Technical breadth', 'Web programming, software engineering, database applications, AI foundations in Python, digital business security, systems deployment.'],
    ],
    subjects: [
      ['Web Programming', 'Building dynamic websites with front-end and back-end technologies.'],
      ['Software Engineering', 'Team-based software design, requirements, testing and delivery practices.'],
      ['Database Applications', 'Relational design, SQL and building applications on top of databases.'],
      ['AI Foundations (Python)', 'Introductory machine learning and AI techniques implemented in Python.'],
      ['Digital Business Security', 'Security risks in business systems and the controls used to manage them.'],
      ['Systems Deployment &amp; Ops', 'Deploying, configuring and operating production systems.'],
      ['Networking Fundamentals', 'How networks work: protocols, addressing, routing and network programming.'],
      ['Capstone: RoboCup', 'Team project building software for a RoboCup robot-soccer competition.'],
    ],
  },
};

export const PROJECTS = [
  {
    id:          'ssl-monitor',
    title:       'SSL/TLS Certificate Monitor',
    tag:         'Python · Security',
    status:      'Live',
    statusColor: 'var(--ok)',
    blurb:       'Parallel certificate expiry checks across many domains, GUI and CLI, zero dependencies.',
    origin:      'An expired certificate took a client-facing banking service down with no warning, mid-morning. Once was enough.',
    overview:    'A desktop GUI and CLI tool that checks SSL/TLS certificate expiry across many domains at once. It came out of managing certificates across live and development banking environments, where an expired cert takes a client-facing service down with no warning.',
    points: [
      'Checks certificate expiry across multiple domains in parallel, so a long domain list still returns in seconds',
      'Full domain manager in the GUI — add, edit, remove and reorder the list without touching a file',
      'Colour-coded results table with configurable warning and critical thresholds',
      'JSON and CSV export for reporting, plus CI-friendly exit codes so it can gate a pipeline',
      'Zero external dependencies — runs on a stock Python install, which matters on locked-down servers',
    ],
    codeLabel: 'Usage',
    code: 'python gui.py                # desktop GUI\npython ssl_monitor.py        # CLI, uses domains.txt\npython ssl_monitor.py -d example.com\npython ssl_monitor.py -f domains.txt --warn-days 60 --json report.json\n\n# scheduled daily check\n0 8 * * * python3 /path/to/ssl_monitor.py -f domains.txt --json /var/log/ssl.json',
    stack:       ['Python', 'Tkinter', 'ssl / socket', 'No dependencies'],
    context:     'Built for certificate management across live and development client environments.',
    statusNote:  'Public on GitHub and in use.',
    links:       [['View on GitHub', 'https://github.com/Vansh-Shah/SSL-Monitor']],
  },
  {
    id:          'iis-log-viewer',
    title:       'IIS Log Viewer',
    tag:         'JavaScript · Log Analysis',
    status:      'Live',
    statusColor: 'var(--ok)',
    blurb:       'Single-file, client-side W3C log triage with a live histogram and substatus decoding.',
    origin:      'Triaging a failing endpoint meant scrolling raw W3C logs by hand while a client waited.',
    overview:    'A single-file, fully client-side viewer for W3C IIS log files, built for fast IP and user-agent triage during an incident. Drop a log in, find the failing endpoint, hand back an answer. Logs never leave the browser, which is what makes it usable on client data.',
    points: [
      'Filter, sort and search requests across a full log file with no server component',
      'Drag-select a time window directly on a live request histogram',
      'Decodes IIS substatus and Win32 codes into readable causes',
      'Surfaces hot and failing endpoints so the pattern shows up before the theory does',
      'Runs entirely in the browser — nothing is uploaded, so client logs stay client logs',
    ],
    codeLabel: 'Where the logs live',
    code: '%SystemDrive%\\inetpub\\logs\\LogFiles\\W3SVC<siteId>\\u_ex*.log\n\n# run it offline\ngit clone https://github.com/Vansh-Shah/iis-log-viewer.git\ncd iis-log-viewer\nstart index.html    # Windows\nopen index.html     # macOS',
    stack:       ['Vanilla JavaScript', 'Canvas', 'Single HTML file'],
    context:     'Built for IIS troubleshooting on client-facing banking web applications.',
    statusNote:  'Public on GitHub with a hosted version.',
    links:       [['View on GitHub', 'https://github.com/Vansh-Shah/iis-log-viewer'], ['Open the tool', 'https://vansh-shah.github.io/iis-log-viewer/']],
  },
  {
    id:          'uvdiag-lock-analysis',
    title:       'UVDiag Lock Analysis',
    tag:         'UniVerse · Diagnostics',
    status:      'Internal',
    statusColor: 'var(--warn)',
    blurb:       'Blocker and deadlock reporting from UniVerse uvdiag captures, with a wait-for graph.',
    origin:      'A live lock storm on UniVerse, and a raw uvdiag capture too slow to read while everything blocked.',
    overview:    'A browser-based analyser for UniVerse uvdiag captures. Reading a raw capture during a live lock incident is slow and error-prone; this reads the whole thing and reports who is blocking whom.',
    points: [
      'Ingests port status, LIST.READU EVERY output and lock daemon logs — or the whole .tar.gz at once',
      'Produces a blocker and deadlock report with a wait-for graph, so the root holder is obvious',
      'Exports to Markdown, HTML or PDF for attaching to a case or a post-incident write-up',
      'Single file, runs in the browser — no install on a production support machine',
    ],
    stack:       ['Vanilla JavaScript', 'Single HTML file', 'UniVerse'],
    context:     'Built for banking support work on UniVerse environments.',
    statusNote:  'Source is internal to Ultradata.',
    note:        'Not public: the tool is written against internal diagnostic formats and stays inside Ultradata. Happy to talk through the approach.',
    links:       [],
  },
  {
    id:          'qr-security',
    title:       'QR Code Security Analysis',
    tag:         'Security Engineering · Research',
    status:      'Published',
    statusColor: 'var(--ok)',
    blurb:       'A 59-page security engineering analysis of QR code systems, from threat model to controls.',
    origin:      'A formal security-engineering brief: take QR codes from threat model through to practical, layered controls.',
    findings: [
      'Mapped the full QR attack surface with STRIDE — spoofing and tampering dominate, because the payload is invisible to the person scanning it',
      'Quishing and physical sticker-replacement need no software vulnerability; they exploit trust in the code itself',
      'Data-flow analysis put the weak point at scan time, where trust is placed but hardest to verify',
      'Recommended layered controls — cryptographic signing and PKI where feasible, backed by process and user-facing design, not technology alone',
    ],
    overview:    'A structured security engineering analysis of QR codes in digital systems, completed for the Principles of Security Engineering unit at UNSW. It works from a formal threat model through to layered, practical recommendations.',
    points: [
      'STRIDE threat modelling and attack trees across the full QR code lifecycle',
      'Data flow analysis identifying where trust is actually placed and where it breaks',
      'Real-world attack techniques: quishing, physical sticker replacement, payload delivery',
      'Cryptographic controls and PKI options assessed against practical deployment constraints',
      'Multi-layered recommendations spanning technical controls, process and user-facing design',
    ],
    stack:       ['STRIDE', 'Attack trees', 'PKI', 'Security engineering'],
    context:     'Principles of Security Engineering, UNSW Master of Cybersecurity.',
    statusNote:  '59 pages, submitted and marked.',
    links:       [['Download report (PDF)', 'qr-security-analysis.pdf']],
  },
  {
    id:          'robocup',
    title:       'RoboCup Capstone',
    tag:         'Robotics · Agile',
    status:      '3rd Intl',
    statusColor: 'var(--accent)',
    blurb:       'Third internationally in the 2024 Challenge Shield Division with RMIT RedBackBots.',
    origin:      'Get a multidisciplinary robotics team funded and competition-ready against a fixed international deadline.',
    overview:    'The RMIT RedBackBots capstone: preparing autonomous robots for the 2024 international RoboCup. The team placed third in the Challenge Shield Division. My side of it was leading the team and getting it to the competition on time and funded.',
    points: [
      'Led a multidisciplinary team through preparation for the international competition',
      'Managed project timelines on Agile cycles across a mixed-skill team',
      'Built the marketing approach and acquired sponsors to fund the campaign',
      'A key driving force behind the team’s 2023 public code release — its first open-source contribution, run through Git',
    ],
    stack:       ['Agile', 'Git', 'Team leadership', 'C++'],
    context:     'Capstone project, RMIT Bachelor of Information Technology.',
    statusNote:  '3rd place, Challenge Shield Division, RoboCup 2024.',
    links:       [['Code release', 'https://github.com/rmit-computing-technologies/redbackbots-coderelease'], ['RedBackBots', 'https://redbackbots.com/']],
  },
  {
    id:          'portfolio',
    title:       'This Portfolio',
    tag:         'Vite · Vanilla JS',
    status:      'Live',
    statusColor: 'var(--ok)',
    blurb:       'Rebuilt around a generated Fingerprint design system, with a real shell in place of a tool grid.',
    origin:      'A résumé-style tool list couldn’t show how the tools and the day job actually connect — and a devtool design system deserved a devtool interaction, not just devtool colours.',
    overview:    'This build takes a generated Fingerprint style spec (cream paper, one orange accent, JetBrains Mono terminal panels) and pushes it past decoration: the Toolkit page is a working shell over the same tool data the grid view uses, and the hero runs a live-shaped incident feed instead of a static screenshot.',
    points: [
      'The Toolkit is a real shell — ls, cd, cat, tree, help, tab-completion and command history over the same 30 tools, with a Grid view fallback a click away',
      'A sudo easter egg with a masked password prompt, three attempts, and a lockout — the password is hidden in the page source, not handed to you',
      'Get it right (there or in the standalone password field) and it throws confetti in the site’s own accent colours',
      'Dark and light themes, toggled in the nav and remembered across visits — a deliberate departure from the spec’s light-only call',
      'The hero terminal rotates through live-shaped P1/P2 incidents on an interval, with a blinking cursor and a cross-fade instead of a static block',
      'Reveal-on-scroll, counting stats, and a pulsing terminal status dot throughout, all behind a full prefers-reduced-motion path',
      'All copy held in one content module, so nothing about the design has to be touched to update it',
    ],
    stack:       ['Vite', 'Vanilla JS', 'CSS custom properties', 'IntersectionObserver'],
    context:     'Personal site. Rebuilt around a generated Fingerprint design system — testing how far a devtool aesthetic can carry a support/banking-incident narrative, and giving it a real interaction to match, not just its colours.',
    statusNote:  'Live on GitHub Pages and still changing.',
    links:       [['View on GitHub', 'https://github.com/Vansh-Shah/VanshShah-Portfolio']],
  },
  {
    id:          'azure-cert-monitor',
    title:       'Azure Certificate Monitor',
    tag:         'Azure · Security · Networking',
    status:      'Coming up',
    statusColor: 'var(--accent)',
    blurb:       'My SSL/TLS monitor rebuilt as a scheduled, cloud-hosted service on Azure, designed to run entirely on free tiers.',
    origin:      'The desktop monitor only works when someone remembers to run it. The next step is a service that checks on a schedule, keeps history and raises the alarm by itself.',
    overview:    'A planned build that takes my SSL/TLS Certificate Monitor from a tool I run to a service that runs itself. A timer-triggered Azure Function checks a list of domains every day, stores each result, and sends an alert when a certificate is close to expiry. A small dashboard behind a sign-in shows the current state and the history. It is also a deliberate exercise in Azure skills: infrastructure as code, managed identities, least-privilege access and cost control, all within free tiers. This page is the plan, written before the build, and it will be updated as each part gets built.',
    points: [
      'Will run a scheduled check every day from an Azure Function on the Consumption plan, reusing the proven expiry-check logic from the desktop tool',
      'Will check more than expiry: certificate chain, hostname match, protocol version and the issuer, so a misconfigured but unexpired certificate is also caught',
      'Will store every result in Cosmos DB free tier, so expiry trends and past incidents can be seen rather than only today’s snapshot',
      'Will send an alert to a chat webhook at configurable warning and critical thresholds, with a clear message naming the domain and the days left',
      'Will serve a dashboard from Static Web Apps (Free plan) with a colour-coded table and history, protected by built-in sign-in so it is not public',
      'Will use a managed identity with a narrowly scoped role to reach the database, so there are no connection strings or keys in the code or the repository',
      'Will be deployed entirely from Bicep, so the whole environment can be created, reviewed and torn down with a few commands',
      'Will be designed to cost nothing: free-tier services only, a budget alert set at $1, and the paid services deliberately left out and documented as such',
    ],
    codeLabel: 'Planned architecture',
    code: 'timer trigger (daily)\n  -> Azure Function (Python)\n       -> TLS handshake per domain: expiry, chain, hostname, protocol\n       -> managed identity -> Cosmos DB (results, history)\n       -> threshold breached? -> webhook alert\n\nStatic Web App (Free)\n  -> sign-in required\n  -> managed API -> Cosmos DB -> dashboard table + history\n\nBicep deploys: Function App, Cosmos DB, Static Web App, role assignments, budget alert',
    stack:       ['Azure Functions', 'Python', 'Cosmos DB (free tier)', 'Static Web Apps', 'Bicep', 'Managed identity'],
    context:     'A follow-on to my SSL/TLS Certificate Monitor, and a way of building Azure, networking and security skills in the open.',
    statusNote:  'Planned. The build log will be written up here as each piece is finished.',
    note:        'This is a planned project. Nothing on this page is built yet, and the points above describe what it will do, not what it does today.',
    links:       [['See the original monitor', 'https://github.com/Vansh-Shah/SSL-Monitor']],
  },
];
